ISSUE-1 Varazdat Kulidzhoglyan
varobart/practical-minimum-2020-students pull request #1
Opened 2020-12-28 08:33 UTC by varobart

Solved two examples and changed another one

[csc profile](https://my.compscicenter.ru/users/7339/)

2020-12-28 08:45 UTC, VarazdatK requested changes

2020-12-28 08:45 UTC, VarazdatK commented on tasks
> +89 - 89 = 10
miscalculation

2020-12-28 08:48 UTC, varobart commented on tasks
> +89 - 89 = 10
fixed it

2020-12-28 08:49 UTC, VarazdatK approved these changes

2021-02-11 14:36 UTC, dehasi approved these changes

2021-02-11 14:36 UTC, dehasi commented
Сквоште :)

2021-02-13 06:22 UTC, merged